export type Action = {
  id: string;
  label: string;
  description: string;
};

export const ACTION_POOL: Action[] = [
  ["Suivre le couloir éclairé", "Avancer lentement vers les néons qui semblent moins instables."],
  ["Prendre le couloir sombre", "S’éloigner de la lumière et avancer là où le bruit semble venir."],
  ["Longer le mur gauche", "Garder la main contre le mur pour ne pas perdre ses repères."],
  ["Longer le mur droit", "Suivre le mur opposé et mémoriser chaque angle."],
  ["Compter les portes", "Avancer en comptant les portes pour vérifier si le couloir boucle."],
  ["Observer le plafond", "Chercher des fissures, des trappes ou une différence dans les plafonds."],
  ["Écouter les néons", "Rester immobile quelques secondes pour distinguer un autre bruit."],
  ["Courir jusqu’au prochain angle", "Prendre de la distance rapidement avant de reprendre son souffle."],
  ["Marcher très lentement", "Réduire le bruit de ses pas et rester attentif."],
  ["Retourner sur ses pas", "Revenir vers le dernier croisement pour vérifier un détail oublié."],
  ["Tester une poignée", "Essayer doucement d’ouvrir une porte proche."],
  ["Regarder sous une porte", "Chercher une lumière ou un mouvement de l’autre côté."],
  ["Frapper trois fois", "Attendre une éventuelle réponse avant d’entrer."],
  ["Ouvrir une porte entrouverte", "Pousser lentement la porte et observer l’intérieur."],
  ["Bloquer une porte", "Placer un objet devant une porte pour créer un repère."],
  ["Noter un symbole au mur", "Laisser une petite marque pour reconnaître le passage."],
  ["Suivre une flaque", "Regarder d’où vient l’humidité et où elle mène."],
  ["Inspecter une moquette différente", "Examiner une zone où le sol ne ressemble plus au reste."],
  ["Toucher le mur", "Vérifier si une partie du mur semble creuse ou anormalement chaude."],
  ["Examiner une ampoule", "Observer une ampoule qui clignote de façon inhabituelle."],
  ["Se cacher derrière un meuble", "Rester silencieux et attendre que les bruits s’éloignent."],
  ["Éteindre son téléphone", "Économiser la batterie et continuer dans le silence."],
  ["Utiliser la lampe du téléphone", "Éclairer un passage trop sombre pour y voir correctement."],
  ["Prendre une photo du couloir", "Capturer le décor pour comparer les photos plus tard."],
  ["Enregistrer les sons", "Lancer un enregistrement pour vérifier les bruits entendus."],
  ["Regarder l’heure", "Comparer l’heure avec ses précédentes observations."],
  ["Vérifier la batterie", "Calculer combien de temps le téléphone peut encore aider."],
  ["Chercher de l’eau", "Fouiller les coins susceptibles de contenir une bouteille."],
  ["Chercher de la nourriture", "Inspecter les placards, bureaux ou petites pièces."],
  ["Fouiller un bureau", "Ouvrir les tiroirs à la recherche d’objets utiles."],
  ["Fouiller un casier", "Inspecter un vieux casier métallique."],
  ["Regarder derrière les tableaux", "Vérifier si un passage ou un objet est caché derrière."],
  ["Soulever un morceau de moquette", "Chercher une trappe ou un défaut dans le sol."],
  ["Examiner une grille", "Vérifier si une grille d’aération peut mener quelque part."],
  ["Suivre le courant d’air", "Marcher vers l’endroit où l’air semble circuler."],
  ["Chercher une température différente", "Repérer une pièce légèrement plus froide ou plus chaude."],
  ["S’asseoir quelques secondes", "Récupérer son calme avant de reprendre l’exploration."],
  ["Faire quelques étirements", "Réduire la fatigue avant une longue marche."],
  ["Boire une réserve", "Consommer une boisson trouvée pour récupérer un peu."],
  ["Manger une petite réserve", "Garder une partie de la nourriture pour plus tard."],
  ["Partager sa nourriture avec quelqu’un", "Prendre le risque de faire confiance à une silhouette."],
  ["Appeler dans le couloir", "Lancer un appel pour savoir si quelqu’un est proche."],
  ["Suivre une voix", "Avancer vers une voix lointaine sans savoir qui parle."],
  ["Éviter la voix", "Changer de direction pour rester seul."],
  ["Suivre des traces au sol", "Observer de petites traces et voir où elles mènent."],
  ["Comparer deux chemins", "Étudier les deux directions avant de choisir."],
  ["Choisir l’escalier", "Descendre l’escalier vers un niveau inconnu."],
  ["Remonter l’escalier", "Monter pour chercher un autre environnement."],
  ["Attendre devant l’ascenseur", "Observer les portes et écouter derrière."],
  ["Appuyer sur un bouton", "Tester si l’ascenseur fonctionne encore."],
  ["Entrer dans l’ascenseur", "Monter ou descendre sans savoir quel étage attend."],
  ["Chercher une trappe", "Examiner le plafond d’une petite pièce."],
  ["Passer sous une barrière", "Se glisser dans une zone normalement inaccessible."],
  ["Enjamber un obstacle", "Continuer malgré un passage encombré."],
  ["Ramper dans un passage étroit", "Explorer un tunnel que personne n’a l’air d’utiliser."],
  ["Rebrousser chemin au passage étroit", "Refuser de s’engager dans un espace trop confiné."],
  ["Tester le sol", "Avancer en vérifiant chaque dalle devant soi."],
  ["Sauter par-dessus une zone humide", "Éviter le sol détrempé."],
  ["Traverser la zone humide", "Avancer directement malgré le sol glissant."],
  ["Suivre les néons jaunes", "Choisir la direction où la lumière paraît régulière."],
  ["Suivre les néons blancs", "Changer de zone pour une lumière plus froide."],
  ["Chercher un bruit de ventilation", "Suivre le bourdonnement d’une machine."],
  ["Chercher une machine", "Explorer une pièce qui semble abriter un générateur."],
  ["Observer une horloge", "Vérifier si son fonctionnement paraît normal."],
  ["Suivre les tuyaux", "Repérer la direction d’un réseau de conduites."],
  ["Examiner une caméra", "Vérifier si une caméra semble encore fonctionner."],
  ["Faire un signe à une caméra", "Tester si quelque chose réagit à sa présence."],
  ["Écrire un message sur le mur", "Laisser une information pour un éventuel autre survivant."],
  ["Chercher un autre message", "Suivre les inscriptions laissées par quelqu’un d’autre."],
  ["Effacer une marque", "Retirer un repère qui pourrait attirer l’attention."],
  ["Créer un faux chemin", "Poser volontairement un objet dans une autre direction."],
  ["Cacher un objet", "Déposer une réserve à un endroit reconnaissable."],
  ["Changer de chaussures", "Utiliser une paire trouvée si elle paraît plus adaptée."],
  ["Examiner ses vêtements", "Vérifier s’ils ont changé depuis son arrivée."],
  ["Regarder son reflet", "Observer un miroir pour détecter quelque chose d’étrange."],
  ["Éviter les miroirs", "Choisir de ne pas regarder les surfaces réfléchissantes."],
  ["Entrer dans une pièce vide", "Explorer une salle sans meuble ni bruit."],
  ["Entrer dans une salle meublée", "Fouiller une pièce qui semble avoir été utilisée."],
  ["Fermer une porte derrière soi", "Limiter les bruits venant du couloir."],
  ["Laisser la porte ouverte", "Garder une sortie visible pour pouvoir revenir."],
  ["Attendre que les néons s’arrêtent", "Profiter d’un instant de noir complet pour écouter."],
  ["Avancer pendant le clignotement", "Profiter des changements de lumière pour progresser."],
  ["Suivre une odeur de propre", "Chercher l’origine d’une odeur inhabituelle."],
  ["Suivre une odeur humide", "Explorer un secteur qui semble proche d’une fuite."],
  ["Chercher une fenêtre", "Vérifier si une ouverture donne réellement sur l’extérieur."],
  ["Toucher une fenêtre", "Observer si le verre est froid ou anormalement chaud."],
  ["Chercher une sortie de secours", "Inspecter les murs pour un panneau ou une porte."],
  ["Suivre un panneau", "Prendre au sérieux une flèche qui semble indiquer une direction."],
  ["Ignorer un panneau", "Considérer le panneau comme un piège et continuer ailleurs."],
  ["Retourner dans une zone connue", "Revenir dans un endroit où les repères sont plus fiables."],
  ["Choisir une direction au hasard", "Prendre un chemin sans chercher de logique."],
  ["Faire pile ou face", "Laisser le hasard décider entre deux couloirs."],
  ["Marquer chaque virage", "Créer un système de repères pour éviter une boucle."],
  ["Tester si le couloir boucle", "Repasser volontairement par les mêmes endroits."],
  ["Chercher une zone calme", "Trouver un endroit pour souffler et observer."],
  ["Chercher une zone bruyante", "Explorer un secteur où quelque chose semble fonctionner."],
  ["Suivre une lumière rouge", "Se diriger vers une faible lumière colorée."],
  ["Suivre une lumière bleue", "Explorer un passage éclairé d’une couleur inhabituelle."],
  ["Attendre derrière un angle", "Observer le passage avant de décider."],
  ["Avancer malgré la peur", "Continuer tout droit sans se laisser distraire par les bruits."],
].map(([label, description], index) => ({
  id: String(index + 1),
  label,
  description,
}));

export function pickActions(turn: number): Action[] {
  const result: Action[] = [];
  const start = (turn * 17) % ACTION_POOL.length;
  for (let offset = 0; result.length < 4; offset += 1) {
    const action = ACTION_POOL[(start + offset * 23 + turn * 7) % ACTION_POOL.length];
    if (!result.some((item) => item.id === action.id)) result.push(action);
  }
  return result;
}
